raw_data_dir: 'mppi_data/'
# Total traj len = future + past + 1 (current)
future_traj_len: 50
past_traj_len: 50
skip_frames: 5

split:
  train:
    - 'train_smallgrid'
  valid:
    - 'valid_smallgrid'

map:
  width: 32 # in meters
  height: 32
  resolution: 0.25
