#raw_data_dir: 'sinu_data/'
raw_data_dir: 'sinu_data_sid/'
# Total traj len = future + past + 1 (current)
future_traj_len: 50
past_traj_len: 50
skip_frames: 5

split:
  train:
    - 'sinu_data/train_smallgrid'
#    - 'sinu_data_speed/train_smallgrid'
#    - 'sinu_data_steer/train_smallgrid'
  valid:
#    - 'sinu_data/valid_smallgrid'
#    - 'sinu_data_speed/valid_smallgrid'
    - 'sinu_data_steer/valid_smallgrid'

map:
  width: 32 # in meters
  height: 32
  resolution: 0.25
#  resolution: 16 ## make the map useless. Save one pixel.
