goal_w: 1.0 ## weight on the terminal goal cost
# goal_w: 0.5 ## weight on the terminal goal cost
#goal_w: 0.01 ## weight on the terminal goal cost
speed_w: 1.0 ## weight with which target speed will be tracked
roll_w: 0.0 ## weight on roll index but also controls for lateral acceleration limits.. something to think about is how longitudenal accel affects accel limits..
lethal_w: 5 # weight on lethal stuff. Note that this is applied to a piecewise function which is :  1/cos(surface angle) for SA < thresh and 1000 for SA > thresh
speed_target: 10.0 ## target speed in m/s
critical_SA: 2.0 # 0.5 is the critical slope angle 1/cos(angle) is used for state cost evaluation
critical_RI: 1.0 ## limiting ratio of lateral to vertical acceleration