goal_w: 1.0 ## weight on the terminal goal cost
speed_w: 0.0 ## weight with which target speed will be tracked
roll_w: 100.0 ## weight on roll index but also controls for lateral acceleration limits.. something to think about is how longitudenal accel affects accel limits..
stop_w: 0.0 ## weight on actually lethal things like people, trees, rocks and so on. Set to 1000.0 and query the min(Sampling.total_cost) > 1000.0 to know if all trajs are bad
lethal_w: 0.0 # weight on lethal stuff. Note that this is applied to a piecewise function which is :  1/cos(surface angle) for SA < thresh and 1000 for SA > thresh
speed_target: 10.0 ## target speed in m/s
critical_SA: 1.15 # 0.5 is the critical slope angle 1/cos(angle) is used for state cost evaluation
critical_RI: 1.0 ## limiting ratio of lateral to vertical acceleration
car_bb_width: 2.0
car_bb_length: 3.0
critical_vert_acc: 3.5
critical_vert_spd: 0.15