wheelbase: 2.6
throttle_to_wheelspeed: 20.0
steering_max: 0.6
dt: 0.05
D: 0.8
B: 6.8
C: 1.5
lf: 1.3
lr: 1.3
Iz: 1.0
LPF_tau: 1.0
res_coeff: 0.0
drag_coeff: 0.0
type: "noslip3d" ## other option is noslip3d