map_name: "small_island"
map_size: 64
map_res: 0.25
map_res_hitl: 0.25
elevation_range: 4.0
layers:
  color: 3
  elevation: 1
  semantics: 3
  costmap: 1
topic_name: "/grid_map_occlusion_inpainting/all_grid_map"