wheelbase: 2.6
throttle_to_wheelspeed: 20.0
steering_max: 0.6
dt: 0.1

# network:
#   state_feat: ['x', 'y', 'th', 'vx', 'wy', 'ay', 'az']
#   control_feat: ['steer', 'throttle']

#   class: BasicMLP
#   net_kwargs:
#     hidden_depth: 1
#     hidden_dim: 256
#     batch_norm: False

# network:
#  state_feat: ['vx', 'vy', 'vz']
#  control_feat: ['steer', 'throttle']
#  use_normalizer: False

#  class: ResidualMLP
#  net_kwargs:
#    hidden_depth: 2
#    hidden_dim: 32
#    batch_norm: True

network:
 state_feat: ['vx', 'vy', 'vz']
 control_feat: ['steer', 'throttle']
 use_normalizer: False

 class: ContextMLP
 net_kwargs:
   hidden_depth: 2
   hidden_dim: 32
   batch_norm: True

# network:
#   state_feat: ['vx', 'vy', 'vz', 'ax', 'ay', 'az', 'wx', 'wy', 'wz']
#   control_feat: ['steer', 'throttle']
#   use_normalizer: True

#   class: DeltaMLP2
#   net_kwargs:
#     hidden_depth: 1
#     hidden_dim: 256
#     batch_norm: True


#network:
#  state_feat: ['vx', 'vy', 'vz', 'ax', 'ay', 'az', 'wx', 'wy', 'wz']
#  control_feat: ['steer', 'throttle']
#  use_normalizer: True
#  class: BasicMLP
#  net_kwargs:
#    hidden_depth: 3
#    hidden_dim: 128
#    batch_norm: False